//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDIColaboradorAcciones
    {
        public int idAccion { get; set; }
        public Nullable<int> idPDI { get; set; }
        public Nullable<int> metodologia { get; set; }
        public Nullable<int> habilidad { get; set; }
        public string acciones { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<int> avance { get; set; }
        public string accionesRealizadas { get; set; }
    }
}
